# Generated by Django 3.2.16 on 2022-12-29 17:27

import appsite.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('my', 'Продаю личный автомобиль'), ('sell', 'Автомобиль приобретен на продажу')], max_length=50)),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('vin_body', models.CharField(max_length=30)),
                ('gos_number', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('mileage', models.IntegerField()),
                ('condition', models.CharField(max_length=30)),
                ('pts', models.CharField(choices=[('Original', 'Оригинал'), ('Duplicate', 'Дубликат'), ('electronic', 'Электронный')], max_length=30)),
                ('score_pts', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('number_phone', models.CharField(max_length=30)),
                ('published_date', models.DateTimeField()),
                ('communication_method', models.CharField(blank=True, choices=[('phone', 'По телефону и в сообщениях'), ('message', 'В сообщениях')], max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=appsite.models.user_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appsite.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('number_flat', models.IntegerField()),
                ('owner_or_agent', models.CharField(max_length=30)),
                ('communication_method', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('published_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
