# Generated by Django 3.2.16 on 2023-01-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fresh',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('old', 'С пробегом')], max_length=50),
        ),
    ]
