# Generated by Django 3.2.16 on 2023-01-01 17:59

import appsite.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appsite', '0002_car_fresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scooters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('vin_body', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('type_scooter', models.CharField(choices=[('scooter', 'Скутер'), ('maksi-scooter', 'Макси-скутер'), ('moped', 'Мопед'), ('minibike', 'Минибайк')], max_length=50)),
                ('year', models.IntegerField()),
                ('type_engine', models.CharField(choices=[('petrol', 'Бензин'), ('electro', 'Электро')], max_length=30)),
                ('power', models.IntegerField()),
                ('volume_engine', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('condition', models.CharField(max_length=30)),
                ('pts', models.CharField(choices=[('Original', 'Оригинал'), ('Duplicate', 'Дубликат'), ('electronic', 'Электронный')], max_length=30)),
                ('score_pts', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('number_phone', models.CharField(max_length=30)),
                ('communication_method', models.CharField(blank=True, choices=[('phone', 'По телефону и в сообщениях'), ('message', 'В сообщениях')], max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryScooters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=appsite.models.user_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appsite.scooters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
