# Generated by Django 3.2.16 on 2023-01-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0003_galleryscooters_scooters'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooters',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
