# Generated by Django 3.2.16 on 2023-01-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooters',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
