# Generated by Django 3.2.16 on 2023-01-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0006_auto_20230102_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
