# Generated by Django 3.2.16 on 2023-01-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0008_remove_car_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_image',
            new_name='category_image_car',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_car',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_image_scooters',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_scooters',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
